buildDebSbuild defaultTargets: 'bullseye-armhf bullseye-arm64',
               defaultRunLintian: true,
               defaultStyleCheckDirs: 'src test',
               defaultScaWbdevTarget: 'bullseye-armhf',
               defaultClangTidyPreHook: 'export CLANG_TIDY_EXTRA_ARG=-I/rootfs/bullseye-armhf/usr/include',
               defaultRunCoverage: true,
               defaultCoverageMin: '73',
               defaultDoCoverallsReporting: false,
               defaultBuildNode: 'heavy-duty',
               defaultWbdevImage: 'contactless/devenv:latest_bullseye'
